Repository ayush-agarwal-190/hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#23 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#22 Sanjay add validation for email and phone number
  index.html
  js/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#26 <KIRTI KAMAL>
  hacktober.html
Labels: hacktoberfest, hacktoberfest-accepted, issue

#25 added required attribute
  .vscode/settings.json
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, issue

#30 bootstrap support added
  css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#35 Updated title and added favicon image
  images/favicon.png
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#45 Update index.html
  index.html
Labels: bug, hacktoberfest, hacktoberfest-accepted

#37 beatiful footer added
  .vscode/settings.json
  css/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#47 Update style.css
  css/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#46 fix some css bugs
  CONTRIBUTING.md
  fitness.html
  index.html
Labels: bug, hacktoberfest, hacktoberfest-accepted

#53 Scrolling button added
  arrow.png
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#62 lorem
  fitness.html
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#59 vivek contributed
  CONTRIBUTING.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#58 form.html
  form.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#61 fixed the bg and info btn color
  fitness.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#69 updated fitness.html
  fitness.html
  hacktober.html
Labels: enhancement, hacktoberfest

#68 made some changes in the background and form fixed style of header
  css/style.css
  images/1.jpg
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#66 Update fitness.html
  fitness.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#64 Hacktoberfest-2022
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#55 calc web check
  web.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#73 Fitness Center Front-end
  Fitness Center/img/bg.jpeg
  Fitness Center/img/logo.png
  Fitness Center/index.html
  Fitness Center/style.css
Labels: enhancement, hacktoberfest

#72 Github Profile Search
  Github Profile Search/index.html
  Github Profile Search/script.js
  Github Profile Search/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#75 Fixed the footer design and it is auto responsive
  css/style.css
  index.html
Labels: enhancement, hacktoberfest
